### ISSUE TITLE
Date maths blows up

### ISSUE THREAD

**Issue by badguy99** [badguy99/octocost#2]
```
2020-04-01 23:24:13.159965 WARNING octocost: ------------------------------------------------------------
2020-04-01 23:24:13.183449 WARNING octocost: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 766, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/octocost/octocost.py", line 29, in cost_and_usage_callback
    self.yesterday = datetime.date(today.year, today.month, today.day-1)
ValueError: day is out of range for month
2020-04-01 23:24:13.191171 WARNING octocost: ------------------------------------------------------------

Should use time delta for date maths.
```

**Comment by badguy99** [comment]
Fixed in v0.1.3
